baseurl             = "http://lockwood.me/"
builddrafts         = false
canonifyurls        = true
contentdir          = "content"
languageCode        = "en-GB"
layoutdir           = "layouts"
publishdir          = "public"
theme               = "cocoa-hugo-theme"
author              = "Alex Lockwood"
title               = "Alex Lockwood"
pygmentsuseclasses  = true
#disqusshortname     = "cocoaexamplesite"
pluralizelisttitles = false
#googleAnalytics     = "UA-123-45"

[permalinks]
blog  = "blog/:slug/"

[[menu.main]]
name                   = "Blog"
weight                 = -120
identifier             = "blog"
url                    = "/blog/"

[[menu.main]]
name                   = "About"
weight                 = -110
identifier             = "about"
url                    = "/about/"

[[menu.main]]
name                   = "Code"
weight                 = -100
identifier             = "code"
url                    = "/code/"

[params]
include_rss            = true                          # include RSS <link> tag in <head> and show RSS icon
latestpostscount       = 5                             # how many posts to display on the home page
i18n_flags             = false                         # whether to display small country flags for available translations
author                 = "Alex Lockwood"
cachebuster            = true                          # add the current unix timestamp in query string for cache busting css assets
dateform               = "Jan 2, 2006"
dateformfull           = "Mon Jan 2 2006 15:04:05 MST"
description            = "Computer Scientist at University of Southampton"
email                  = "you@example.space"
extracssfiles          = [ "/css/override.css" ]       # In your `static` directory, add/remove files as necessary.
faviconfile            = "img/leaf.ico"
github                 = "//github.com/lockwooda"
#instagram              = "//instagram.com/you"
#px500                  = "//500px.com/username"
lang                   = "en"
linkedin               = "//linkedin.com/in/alex-lockwood-6a4137163/"
noshowreadtime         = false                         # if true, don't show "<x> minutes read" in posts
selfintro              = "Hi! I'm Alex Lockwood. I'm an Undergraduate Computer Scientist at the University of Southampton. I enjoy coding, mathematics and problem solving."                            # appears in the site header when set to a non-empty string
#twitter                = "//twitter.com/you"
#mastodon               = "//example.com/@you"

highlightjs            = true
# highlightjslanguages = ["go"]                        # additional languages not included in the "common" set
# highlightjsStyle     = "darcula"

avatar                 = "img/profile.jpg" # path to image in static dir e.g img/avatar.png (do not use in the same time as gravatar)
