[build]
    publish = "public/"
    command = "./scripts/build.sh"

[context.production.environment]
    HUGO_VERSION = "0.61.0"
    HUGO_ENV = "production"

[context.deploy-preview.environment]
    HUGO_VERSION = "0.61.0"

[context.branch-deploy.environment]
HUGO_VERSION = "0.61.0"
